[SERIAL]
PORT      = /dev/ttyUSB0
BAUDRATE  = 9600
BYTES     = 8

# possible values: NONE, EVEN, ODD
PARITY    = NONE
STOPBITS  = 1

# time to wait for response after sending command
PAUSETIME = 0.05
TIMEOUT   = 2.0

[CHILLER]
MODEL     = RP1845
